apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: leeroy-web
build:
  artifacts:
  - image: leeroy-web
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
