apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: leeroy-web
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/cloud-deploy-fyndna/docker-registry/leeroy-web
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml
