apiVersion: v1
kind: Service
metadata:
  name: leeroy-web-service
spec:
  type: LoadBalancer
  port: 
  selector:
    app: leeroy-web
  ports:
  - port: 8080
    name: leeroy-web
    protocol: TCP
    targetPort: 8080
  
  

